lwr:
  # Publish all joint states -----------------------------------
  kuka_joint_state_controller:
    type: lwr_controllers/KUKAJointStateController
    publish_rate: 100  
    root_name: lwr_base_link
    tip_name: lwr_peg_link

  #   Joint Torque Impedance Controllers
  joint_controllers:
    type: lwr_controllers/JointControllers
    root_name: lwr_base_link
    tip_name: lwr_peg_link
    max_qdot: 1.0
    publish_rate: 100
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3
